/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.ferrybig.javacoding.graphical.decompiler.media;

import me.ferrybig.javacoding.graphical.decompiler.StringLoader;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.JComponent;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author Fernando
 */
public class JavaPane extends javax.swing.JPanel implements CodePane {

	public JavaPane(CodePaneConfig conf) {
		initComponents();
		new StringLoader(conf.getUrl(), textPane::setText, e -> textPane.setText("// " + e)).execute();
	}

	@Override
	public CodePane contentUpdated(URL newUrl) {
		return null;
	}

	@Override
	public JComponent getContent() {
		return this;
	}

	@Override
	public Icon getIcon(boolean hasSources) {
		return null;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        scrollPane = new RTextScrollPane();
        textPane = new RSyntaxTextArea();

        setLayout(new GridBagLayout());

        scrollPane.setFoldIndicatorEnabled(true);
        scrollPane.setLineNumbersEnabled(true);

        textPane.setEditable(false);
        textPane.setColumns(20);
        textPane.setRows(5);
        textPane.setTabSize(4);
        textPane.setText("package we.are.still.loading;\n\n// Loading file...\n\npublic class Loading {\n\n\tpublic static void main(String ... args) {\n\t\tSystem.out.println(\"We are still loading...\");\n\t}\n\n}"); // NOI18N
        textPane.setMarginLineEnabled(true);
        textPane.setPaintMatchedBracketPair(true);
        textPane.setPaintTabLines(true);
        textPane.setSyntaxEditingStyle("text/java");
        scrollPane.setViewportView(textPane);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(scrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RTextScrollPane scrollPane;
    private RSyntaxTextArea textPane;
    // End of variables declaration//GEN-END:variables
}
