/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.ferrybig.javacoding.graphical.decompiler.media;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.net.URL;
import javax.swing.GroupLayout;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import me.ferrybig.javacoding.graphical.decompiler.Config;

/**
 *
 * @author Fernando
 */
public class LoadingPane extends javax.swing.JPanel implements CodePane {

	private final CodePaneConfig conf;

	public LoadingPane(CodePaneConfig conf) {
		initComponents();
		this.conf = conf;
	}

	@Override
	public CodePane contentUpdated(URL newUrl) {
		return conf.setUrl(newUrl).createPane();
	}

	@Override
	public JComponent getContent() {
		return this;
	}

	@Override
	public Icon getIcon(boolean hasSources) {
		return null;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jProgressBar1 = new JProgressBar();
        jLabel1 = new JLabel();

        setLayout(new GridBagLayout());

        jProgressBar1.setIndeterminate(true);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jProgressBar1, gridBagConstraints);

        jLabel1.setText("Still decompiling...");
        add(jLabel1, new GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel1;
    private JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
