/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.ferrybig.javacoding.graphical.decompiler.media;

import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 *
 * @author Fernando
 */
public class TextPane extends javax.swing.JPanel implements CodePane {

	public TextPane(CodePaneConfig conf) {
		initComponents();
		try {
			jTextPane1.setPage(conf.getUrl());
		} catch (IOException ex) {
			Logger.getLogger(TextPane.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	@Override
	public CodePane contentUpdated(URL newUrl) {
		return null;
	}

	@Override
	public JComponent getContent() {
		return this;
	}

	@Override
	public Icon getIcon() {
		return null;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jScrollPane1 = new JScrollPane();
        jTextPane1 = new JTextPane();

        setLayout(new GridBagLayout());

        jTextPane1.setFont(new Font("Monospaced", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane jScrollPane1;
    private JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
