/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.ferrybig.javacoding.graphical.decompiler;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.concurrent.Future;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author Fernando
 */
public class FindDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = -4835269298085063549L;
	private final CodeOverview overview;
	private final Pattern filePattern = Pattern.compile(".*\\.class", Pattern.CASE_INSENSITIVE);

	public FindDialog(java.awt.Frame parent, CodeOverview overview, boolean modal) {
		super(parent, modal);
		this.overview = overview;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new JTextField();
        fileTypes = new JComboBox<>();
        searchButton = new JButton();
        regex = new JCheckBox();
        caseInsensitivity = new JCheckBox();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        textField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                searchSubmit(evt);
            }
        });

        fileTypes.setEditable(true);
        fileTypes.setModel(new DefaultComboBoxModel<>(new String[] { "*.class", "*.java", "*.txt" }));
        fileTypes.setToolTipText("Not implemented at the moment");
        fileTypes.setEnabled(false);
        fileTypes.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                searchSubmit(evt);
            }
        });

        searchButton.setText("Find");
        searchButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                searchSubmit(evt);
            }
        });

        regex.setText("Regex");

        caseInsensitivity.setText("Case insensentive");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 122, Short.MAX_VALUE)
                        .addComponent(caseInsensitivity)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(regex))
                    .addComponent(textField, GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(fileTypes, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(fileTypes, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(regex)
                    .addComponent(caseInsensitivity))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchSubmit(ActionEvent evt) {//GEN-FIRST:event_searchSubmit
		String pattern = textField.getText();
		if (!regex.isSelected()) {
			pattern = Pattern.quote(pattern);
		}
		this.overview.startSearch(Pattern.compile(pattern, caseInsensitivity.isSelected() ? Pattern.CASE_INSENSITIVE : 0), filePattern);
		this.setVisible(false);
    }//GEN-LAST:event_searchSubmit

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox caseInsensitivity;
    private JComboBox<String> fileTypes;
    private JCheckBox regex;
    private JButton searchButton;
    private JTextField textField;
    // End of variables declaration//GEN-END:variables
}
