/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.ferrybig.javacoding.graphical.decompiler;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.text.SimpleDateFormat;
import java.util.logging.LogRecord;
import javax.swing.JLabel;
import static me.ferrybig.javacoding.graphical.decompiler.util.HTMLEscape.escapeHTML;

/**
 *
 * @author Fernando
 */
public class LogRecordPanel extends javax.swing.JPanel {

	private LogRecord record;

	/**
	 * Creates new form LogRecordPanel
	 */
	public LogRecordPanel() {
		initComponents();
	}

	public LogRecord getRecord() {
		return record;
	}

	public void setRecord(LogRecord record) {
		this.record = record;
		date.setText(format.format(record.getMillis()));
		if (record.getParameters() != null && record.getParameters().length > 0) {
			message.setText(java.text.MessageFormat.format(
					record.getMessage(), record.getParameters()));
		} else {
			message.setText(record.getMessage());
		}
		String txt;
		if (record.getThrown() == null) {
			txt = "";
		} else {
			StringWriter writer = new StringWriter();
			record.getThrown().printStackTrace(new PrintWriter(writer));
			txt = writer.toString();
		}
		exception.setText("<html>" + escapeHTML(txt).replace("\n", "<br>"));
	}

	private final SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        icon = new JLabel();
        message = new JLabel();
        date = new JLabel();
        exception = new JLabel();

        setLayout(new GridBagLayout());

        icon.setMaximumSize(new Dimension(32, 32));
        icon.setMinimumSize(new Dimension(32, 32));
        icon.setPreferredSize(new Dimension(32, 32));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        add(icon, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(message, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        add(date, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        add(exception, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel date;
    private JLabel exception;
    private JLabel icon;
    private JLabel message;
    // End of variables declaration//GEN-END:variables
}
